export const wordList = [
    { word: 'Turgid', definition: '1. Swollen, inflamed 2. Pompous, bombastic'},
    { word: 'Extemporize', definition: 'To improvise'},
    { word: 'Platitude', definition: 'Banal, commonplace remark'},
    { word: 'Plolix', definition: 'Lengthy, tedious'},
    { word: 'Esoteric', definition: 'Intelligible only to those with special knowledge'},
    { word: 'Isomorphism', definition: 'A structure preserving mapping between two structures or systems'},
    { word: 'Dichotomy', definition: 'A division or contrast between two things that are or are represented as being opposed or entirely different'},
    { word: 'Purpoted', definition: 'Appearing or stated to be true, though not necessarily so; alleged'},
    { word: 'Ineluctable', definition: 'Unable to be resisted or avoided; inescapable'},
    { word: 'Vitriolic', definition: 'Filled with bitter criticism or malice'},
    { word: 'Palimpsest', definition: 'Something reused or altered but still bearing visible traces of its earlier form'},
    { word: 'Multifarious', definition: 'Having many varied parts or aspects'},
    { word: 'Fulminating', definition: 'Expressing vehement protest'},
    { word: 'Austere', definition: 'Severe or strict in manner or attitude'},
    { word: 'Tacit', definition: 'Understood or implied without being stated'},
    { word: 'Unabashed', definition: 'Not embarrassed, disconcerted, or ashamed'},
    { word: 'Loquacious', definition: 'Tending to talk a great deal; talkative'},
    { word: 'Vociferous', definition: 'Expressing or characterized by vehement opinions; loud and forceful'},
    { word: 'Furtive', definition: 'Attempting to avoid notice or attention, typically because of guilt or a belief that discovery would lead to trouble; secretive'},
    { word: 'Petulant', definition: '(of a person or their manner) childishly sulky or bad-tempered'},
    { word: 'Idiosyncrasy', definition: 'A mode of behaviour or way of thought peculiar to an individual'},
    { word: 'Croon', definition: 'Hum or sing in a soft, low voice, especially in a sentimental manner'},
    { word: 'Staunchly', definition: 'In a very loyal and committed manner'},
    { word: 'Dastardly', definition: 'Wicked and cruel'},
    { word: 'Imbue', definition: 'Inspire or permeate with (a feeling or quality)'},
    { word: 'Vehement', definition: 'Showing strong feeling; forceful, passionate, or intense'},
    { word: 'Terse', definition: 'Sparing in the use of words; abrupt'},
    { word: 'Placate', definition: 'Make (someone) less angry or hostile'},
    { word: 'Engender', definition: 'Cause or give rise to (a feeling, situation, or condition)'},
    { word: 'Oblique', definition: 'Neither parallel nor at right angles to a specified or implied line; slanting'},
    { word: 'Decant', definition: 'Gradually pour (wine, port, or another liquid) from one container into another, typically in order to separate out sediment'},
    { word: 'Ephemeral', definition: 'Lasting for a very short time'},
    { word: 'Confound', definition: 'Cause surprise or confusion in (someone), especially by not according with their expectations'},
    { word: 'Swaths', definition: 'A broad strip or area of something'},
    { word: 'Elusive', definition: 'Difficult to find, catch, or achieve or difficult to remember'},
    { word: 'Entheogen', definition: 'Psychoactive substances that induce alterations in perception, mood, consciousness, cognition, or behavior for the purposes of engendering spiritual development or otherwise in sacred contexts'},
    { word: 'Indelible', definition: '(of ink or a pen) making marks that cannot be removed'},
    { word: 'Inebriate', definition: 'Make (someone) drunk; intoxicate'},
    { word: 'Prosaic', definition: 'Having or using the style or diction of prose as opposed to poetry; lacking imaginativeness or originality'},
    { word: 'Perforce', definition: 'Used to express necessity or inevitability'},
    { word: 'Eludicate', definition: 'Make (something) clear; explain'},
    { word: 'Anthropocentric', definition: 'Regarding humankind as the central or most important element of existence, especially as opposed to God or animals'},
    { word: 'Pernicious', definition: 'Having a harmful effect, especially in a gradual or subtle way'},
    { word: 'Stringent', definition: '(of regulations, requirements, or conditions) strict, precise, and exacting'},
    { word: 'Wryly', definition: 'In a way that expresses dry, especially mocking, humour'},
    { word: 'Proselytise', definition: 'Convert or attempt to convert (someone) from one religion, belief, or opinion to another'},
    { word: 'Deft', definition: 'Neatly skilful and quick in one\'s movements'},
    { word: 'Moulder', definition: 'Slowly decay or disintegrate, especially because of neglect'},
    { word: 'Impel', definition: 'Drive, force, or urge (someone) to do something'},
    { word: 'Fecund', definition: 'Producing or capable of producing an abundance of offspring or new growth; highly fertile or producing many new ideas'},
    { word: 'Prolific', definition: '(of a plant, animal, or person) producing much fruit or foliage or many offspring or present in large numbers or quantities; plentiful'},
    { word: 'Fervour', definition: 'Intense or passionate feeling'},
    { word: 'Sedentary', definition: '(of a person) tending to spend much time seated; somewhat inactive, desk-bound'},
    { word: 'Reverance', definition: 'Deep respect for someone or something'},
    { word: 'Venerate', definition: 'Regard with great respect; revere'},
    { word: 'Apochryphal', definition: '(of a story or statement) of doubtful authenticity, although widely circulated as being true'},
    { word: 'Quandary', definition: 'A state of perplexity or uncertainty over what to do in a difficult situation'},
    { word: 'Contiguous', definition: 'Sharing a common border; touching or together in sequence'},
    { word: 'Teleology', definition: 'The explanation of phenomena in terms of the purpose they serve rather than of the cause by which they arise'},
    { word: 'Assiduous', definition: 'Showing great care and perseverance'},
    { word: 'Gleaned', definition: 'Obtain (information) from various sources, often with great difficulty'},
    { word: 'Palter', definition: '1. Equivocate or prevaricate in action or speech 2. Trifle with'},
    { word: 'Prevaricate', definition: 'Speak or act in an evasive way'},
    { word: 'Meek', definition: 'Quiet, gentle, and easily imposed on; submissive'},
    { word: 'Paramour', definition: 'A lover, especially the illicit partner of a married person'}
];